// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sonneville.Investing.Persistence.EFCore.EntityFrameworkCore;
using System;

namespace Sonneville.Investing.Persistence.EFCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180606233150_Persist_salted_password_hashes")]
    partial class Persist_salted_password_hashes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Sonneville.Investing.Persistence.EFCore.Security.HashedDigest", b =>
                {
                    b.Property<long>("DatabaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cryptor");

                    b.Property<byte[]>("Digest");

                    b.Property<string>("HashingAlgorithm");

                    b.Property<int>("Iterations");

                    b.Property<byte[]>("SaltUsed");

                    b.Property<long>("UserId");

                    b.HasKey("DatabaseId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HashedDigest");
                });

            modelBuilder.Entity("Sonneville.Investing.Persistence.EFCore.Users.ApplicationUser", b =>
                {
                    b.Property<long>("DatabaseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("DatabaseId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Sonneville.Investing.Persistence.EFCore.Security.HashedDigest", b =>
                {
                    b.HasOne("Sonneville.Investing.Persistence.EFCore.Users.ApplicationUser", "User")
                        .WithOne("PasswordDigest")
                        .HasForeignKey("Sonneville.Investing.Persistence.EFCore.Security.HashedDigest", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
