using System;
using Microsoft.EntityFrameworkCore;
using Sonneville.Investing.Persistence.EFCore.Users;

namespace Sonneville.Investing.Persistence.EFCore.EntityFrameworkCore
{
    public interface IDataContext : IDisposable
    {
        IApplicationUserRepository ApplicationUserRepository { get; }
        int SaveChanges();
    }

    public class DataContext : DbContext, IDataContext
    {
        private readonly DatabaseConnectionInfo _databaseConnectionInfo;

        public DataContext(DatabaseConnectionInfo databaseConnectionInfo)
        {
            _databaseConnectionInfo = databaseConnectionInfo;
            ApplicationUserRepository = new ApplicationUserRepository(this);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(_databaseConnectionInfo.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            new FluentModelBuilder<ApplicationUser>(modelBuilder)
                .HasAutoGeneratedProperty(user => user.DatabaseId)
                .HasPrimaryKey(user => user.DatabaseId)
                .HasUnique(user => user.UserName);

            modelBuilder.ForNpgsqlUseSerialColumns();
            base.OnModelCreating(modelBuilder);
        }

        public IApplicationUserRepository ApplicationUserRepository { get; }
    }
}
